#include "config.h"

// ----------------------------------------------------------------------------------------
// Power & Performance – Real mutable variables with default values
// ----------------------------------------------------------------------------------------

long  DELAY_TASK_SYSTEM_TIMING        = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_SYSTEM_TIMING;
bool  TICK_DELAY_TASK_SYSTEM_TIMING   = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_SYSTEM_TIMING;

long  DELAY_TASK_SERIAL_INFOCMD       = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_SERIAL_INFOCMD;
bool  TICK_DELAY_TASK_SERIAL_INFOCMD  = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_SERIAL_INFOCMD;

long  DELAY_TASK_MULTIPLEXERS         = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_MULTIPLEXERS;
bool  TICK_DELAY_TASK_MULTIPLEXERS    = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_MULTIPLEXERS;

long  DELAY_TASK_GYRO0                = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_GYRO;
bool  TICK_DELAY_TASK_GYRO0           = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_GYRO;

long  DELAY_TASK_UNIVERSE             = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_UNIVERSE;
bool  TICK_DELAY_TASK_UNIVERSE        = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_UNIVERSE;

long  DELAY_TASK_GPS                  = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_GPS;
bool  TICK_DELAY_TASK_GPS             = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_GPS;

long  DELAY_TASK_SWITCHES             = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_SWITCHES;
bool  TICK_DELAY_TASK_SWITCHES        = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_SWITCHES;

long  DELAY_TASK_PORTCONTROLLER_INPUT      = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_PORTCONTROLLER_INPUT;
bool  TICK_DELAY_TASK_PORTCONTROLLER_INPUT = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_PORTCONTROLLER_INPUT;

long  DELAY_TASK_STORAGE              = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_STORAGE;
bool  TICK_DELAY_TASK_STORAGE         = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_STORAGE;

bool global_task_sync      = false;
long system_sync_retry_max = 2000;
